---
title: Descargando tu programa al micro:bit
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Descargar a micro:bit
